# Generated by Django 2.2.6 on 2019-10-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=150)),
                ('pregunta_1', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_2', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_3', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=150)),
                ('pregunta_1', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_2', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_3', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_4', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_5', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_6', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_7', models.BooleanField(default=False)),
                ('pregunta_8', models.BooleanField(default=False)),
                ('pregunta_9', models.BooleanField(default=False)),
                ('pregunta_10', models.BooleanField(default=False)),
                ('pregunta_11', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=150)),
                ('pregunta_1', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_2', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_3', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_4', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_5', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_6', models.CharField(choices=[('MB', 'Muy bien'), ('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('MM', 'Muy mal')], max_length=10)),
                ('pregunta_7', models.BooleanField(default=False)),
                ('pregunta_8', models.BooleanField(default=False)),
                ('pregunta_9', models.BooleanField(default=False)),
            ],
        ),
    ]
